### ISSUE TITLE
Emojis (or any surragate pair) breaks the plugin

### ISSUE THREAD

**Issue by Alexey-T** [ThaiDat/cuda_transpose#11]
Emojis are encoded in UTF16 (internal Cud's data) via surrogate pairs. ie 2 widechars. when plugin tries to move ascii letter "into emoji", error is raised by Cud.
remedy: plugin must skip 2 widechars in this case.

test file.
[em.txt](https://github.com/ThaiDat/cuda_transpose/files/10851367/em.txt)

place caret on first ':' and move it to the right 10 times.

![Screenshot from 2023-02-28 17-37-24](https://user-images.githubusercontent.com/4154978/221886462-73ecea78-a66a-4b8e-8082-77bb0c40699c.png)

@jairomartineza - it is report for your future code too.

**Comment by ThaiDat** [comment]
@Alexey-T I need help with the API. 
For example, I have an text file like below:
`😂shavsv`
If I call `ed.get_text_substr(0,0,2,0)`, it will return `😂`.  And if I call `ed.get_text_substr(0,0,1,0)` it will return the first byte of the surrogate pair that represent `😂`.
So, I assume that `get_text_substr` return bytes within the given range in the internal CudaText data. It's weird because naturally I think it should return the text (not bytes) within the given range that I see on the editor. For example when I call `ed.get_text_substr(0,0,2,0)` it should return `😂s`. It's strange if I put my caret at line 1 after the first character but CudaText tell me that I am actually at line 1 column 3.
![image](https://user-images.githubusercontent.com/18527312/222035230-d98c6460-7e1f-4ad7-b240-a0e80b4040ec.png)
(Sublime)
![image](https://user-images.githubusercontent.com/18527312/222035320-6870666a-2c16-4124-84bc-1f4abe35c9b1.png)
Can we make a fix from CudaText side as an enhancement. If no, I will put some UTF-16 detector to my plugin and make it work with current design.

**Comment by Alexey-T** [comment]
Cud has UTF16 internal storage. so substr(0,0,2,0) gets 2 utf16 chars , it is the 2-widechar emoji. fix for Cud is not needed here. please adapt to utf16 data.

**Comment by Alexey-T** [comment]
>It's strange if I put my caret at line 1 after the first character but CudaText tell me that I am actually at line 1 column 3.

because Cud tells you position in utf16 chars!

**Comment by ThaiDat** [comment]
Got it.
