### ISSUE TITLE
readme.txt: add this info

### ISSUE THREAD

**Issue by Alexey-T** [ThaiDat/cuda_transpose#5]
1. 'Sublime text'->'Sublime Text'

2. add: `If with multi-carets, some caret don't have the selection, it will be treated differently from Sublime Text: it will be treated as empty selection, while in ST4 this caret will get the forced selection from the word under caret.` But consider to make it like in ST (not sure)

**Comment by ThaiDat** [comment]
README updated.

I think we shouldn't use the forced selection as Sublime Text. Because:
- It's risky and confusing. Especially when the forced selection overlap with some existed selection. (Ex: ab|cd`efg`hi|jk)
- It has no practical use. I find no reason for users to setup such scenarios. If they do, they should make selection.
